# Random Forest Regression on the World Population

For the final test of the week, we'll learn how decision trees can be expanded upon as simple classifiers in order to create an [ensemble](https://en.wikipedia.org/wiki/Ensemble_learning) model know as a Random Forest. Like our previous coding challenges, we train this new model using the world population data from the Analyse Supplementary Exam. 

### Imports

In [0]:
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestRegressor

In [0]:
population_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/world_population.csv', index_col='Country Code')
meta_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/metadata.csv', index_col='Country Code')

In [111]:
population_df.head()

1960       1961  ...        2016        2017
Country Code                        ...                        
ABW             54211.0    55438.0  ...    104822.0    105264.0
AFG           8996351.0  9166764.0  ...  34656032.0  35530081.0
AGO           5643182.0  5753024.0  ...  28813463.0  29784193.0
ALB           1608800.0  1659800.0  ...   2876101.0   2873457.0
AND             13411.0    14375.0  ...     77281.0     76965.0

[5 rows x 58 columns]

In [112]:
meta_df.head()

Region  ...                                      Special Notes
Country Code                             ...                                                   
ABW           Latin America & Caribbean  ...  Mining is included in agriculture\r\r\r\nElect...
AFG                          South Asia  ...  Fiscal year end: March 20; reporting period fo...
AGO                  Sub-Saharan Africa  ...                                                NaN
ALB               Europe & Central Asia  ...                                                NaN
AND               Europe & Central Asia  ...  WB-3 code changed from ADO to AND to align wit...

[5 rows x 3 columns]

### Question 1

As we've seen previously, the world population data spans from 1960 to 2017. We'd like to build a predictive model that can give us the best guess at what the world population in a given year was. However, as a slight twist this time, we want to compute this estimate for only _countries within a given income group_. To do this, similar to our previous coding challenges, we need to partition our data such that we have testing data which is reserved for our model's evaluation.  

First, however, we need to formulate our data such that the sklearn's `RandomForestRegressor` class can train on our data. To do this, we will write a function that takes as input an income group and return a 2-d numpy array that contains the year and the measured population.

_**Function Specifications:**_
* Should take a `str` argument, called `income_group` as input and return a numpy `array` type as output.
* Set the default argument of `income_group` to equal `'Low income'`.
* If the specified value of `income_group` does not exist, the function must raise a `ValueError`.
* The array should only have two columns containing the year and the population, in other words, it should have a shape `(?, 2)` where `?` is the length of the data.
* The values within the array should be of type `np.int64`. 

_**Further Reading:**_

Data types are associated with memory allocation. As such, your choice of data type affects the precision of computations in your program. For example, the `np.int` data type in numpy can only store values between -2147483648 to 2147483647 and assigning values outside this range for variables of this data type may cause run-time errors. To avoid this, we can use data types with larger memory capacity e.g. `np.int64`.

https://docs.scipy.org/doc/numpy/user/basics.types.html

In [0]:
def get_year_pop_by_income(income_group='Low income'):
    
  x = list(['High income','Low income','Lower middle income', 'Upper middle income'])
  if income_group not in x:
    raise ValueError('income group does not exist in df')
  else:
    
    df2 = pd.DataFrame(meta_df)
    df3 = pd.DataFrame(population_df)
    df2 = df2[df2['Income Group'] == income_group]
    #df3 = df3[df3.index.sort_index() == df2.index.sort_index()]
    df3 = df3.sort_index()
    df2 = df2.sort_index()

    a = df3.index.searchsorted(df2.index)
    
    df3 = df3.iloc[a]
    df = pd.melt(df3, var_name='Year', value_name='Population')
    df =df.groupby(['Year'])[['Population']].sum()
    #df = df.drop(['Country Code'],axis=1) 
    
    array_1 = df['Population'].astype(np.int64)  
    array_2 = df.index.astype(np.int64)
    
    df=pd.DataFrame({'Year' : array_2,'Population' : array_1},dtype='int64')
    return np.array(df)
    return df3
 

In [114]:
get_year_pop_by_income('High income')

array([[      1960,  769889923],
       [      1961,  781225329],
       [      1962,  791207437],
       [      1963,  801108277],
       [      1964,  810900987],
       [      1965,  820309686],
       [      1966,  829088382],
       [      1967,  837479954],
       [      1968,  844905494],
       [      1969,  854059674],
       [      1970,  862276721],
       [      1971,  871169187],
       [      1972,  880246152],
       [      1973,  888486025],
       [      1974,  897803169],
       [      1975,  906573084],
       [      1976,  913843314],
       [      1977,  921330504],
       [      1978,  928906293],
       [      1979,  936836246],
       [      1980,  944587066],
       [      1981,  952368316],
       [      1982,  959759971],
       [      1983,  966754949],
       [      1984,  973423742],
       [      1985,  980143630],
       [      1986,  987194728],
       [      1987,  994242786],
       [      1988, 1001421456],
       [      1989, 1009036892],
       [  

_**Expected Outputs:**_
```python
get_year_pop_by_income('High income')
```
> ```
array([[      1960,  769889923],
       [      1961,  781225329],
       [      1962,  791207437],
       [      1963,  801108277],
       ...
       [      2015, 1211252041],
       [      2016, 1218629612],
       [      2017, 1225514228]])
```




### Question 2

Now that we have have our data, we need to split this into a set of variables we will be training on, and the set of variables that we will make our predictions on.

Unlike the previous coding challenges, a friend of our has indicated that sklearn has its own built-in functionality for creating training and testing sets. Here, using the `train_test_split` [method](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html), we can easily shuffle and randomly choose a subset of the data as the test set.   

Using this knowledge, write a function which uses sklearn's `train_test_split` [method](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) internally, and that will take as input a 2-d numpy array and return four variables in the form of `(X_train, y_train), (X_test, y_test)`, where `(X_train, y_train)` are the features / response of the training set, and `(X-test, y_test)` are the feautes / response of the testing set. 

**Important Note:** Due to the random initialisation process used within sklearn's `train_test_split` method, you will need to fix the value of the `random_state` argument in order to get repeatable and predictable results. 


_**Function Specifications:**_
* Should take a 2-d numpy `array` as input.
* Should use sklearn's `train_test_split` [method](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html).
* Set `random_state` to equal `42` for this internal method.  
* Should return two `tuples` of the form `(X_train, y_train), (X_test, y_test)`.
* `(X_test, y_test)` should contain 1% of the input array. They should also be the form of an `array`, and not as a single value.


In [0]:


def sklearn_feature_response_split(arr):
  arr = np.array(arr)
  from sklearn.model_selection import train_test_split
  if arr.shape == (len(arr),2):
    X_train, X_test, y_train, y_test = train_test_split(arr[0:,0], arr[0:,1], test_size=0.01, random_state=42)
    return (np.array(X_train), np.array(y_train)), (np.array(X_test), np.array(y_test))
  else:
    return 'all'
    
 
  

In [125]:
data = get_year_pop_by_income('High income');
sklearn_feature_response_split(data)

((array([1965, 1990, 1973, 1994, 2015, 1987, 1991, 2005, 1972, 2007, 1963,
         2003, 1986, 1968, 1977, 1966, 1964, 2000, 1979, 1996, 2008, 1997,
         2013, 1975, 1969, 1976, 1984, 1993, 2014, 2012, 1985, 1971, 1992,
         2010, 2009, 1989, 2001, 1961, 1981, 1962, 2004, 1999, 1995, 1983,
         2006, 1970, 1982, 1978, 2016, 1980, 1967, 2002, 1974, 1988, 2011,
         1998]),
  array([ 820309686, 1017092667,  888486025, 1048121445, 1211252041,
          994242786, 1025345408, 1131426281,  880246152, 1149238990,
          801108277, 1115390519,  987194728,  844905494,  921330504,
          829088382,  810900987, 1092825678,  936836246, 1064630661,
         1158965286, 1071969568, 1196212921,  906573084,  854059674,
          913843314,  973423742, 1040349480, 1203819897, 1188796100,
          980143630,  871169187, 1031949811, 1175649232, 1167712409,
         1009036892, 1100293969,  781225329,  952368316,  791207437,
         1123325037, 1085992668, 1057290586,  966754949,

_**Expected Outputs:**_
```python
data = get_year_pop_by_income('High income')
sklearn_feature_response_split(data)
```
> ```
((array([1965, 1994, 1973, 2004, 2012, 1997, 1985, 2006, 1972, 2008, 1963,
         1996, 1991, 1968, 1977, 1966, 1964, 2001, 1979, 1990, 2009, 2010,
         2014, 1975, 1969, 1987, 1986, 1976, 1984, 1993, 2015, 2000, 1971,
         1992, 2016, 2003, 1989, 2013, 1961, 1981, 1962, 2005, 1999, 1995,
         1983, 2007, 1970, 1982, 1978, 2017, 1980, 1967, 2002, 1974, 1988,
         2011, 1998]),
  array([ 820309686, 1048121445,  888486025, 1123325037, 1188796100,
         1071969568,  980143630, 1140084827,  880246152, 1158965286,
          801108277, 1064630661, 1025345408,  844905494,  921330504,
          829088382,  810900987, 1100293969,  936836246, 1017092667,
         1167712409, 1175649232, 1203819897,  906573084,  854059674,
          994242786,  987194728,  913843314,  973423742, 1040349480,
         1211252041, 1092825678,  871169187, 1031949811, 1218629612,
         1115390519, 1009036892, 1196212921,  781225329,  952368316,
          791207437, 1131426281, 1085992668, 1057290586,  966754949,
         1149238990,  862276721,  959759971,  928906293, 1225514228,
          944587066,  837479954, 1107836355,  897803169, 1001421456,
         1181451343, 1078927765])),
 (array([1960]), array([769889923])))
 ```

### Question 3

Now that we have formatted our data, we can fit a model using sklearn's `DecisionTreeRegressor` class. We'll write a function that will take as input the features and response variables that we created in the last question, and return a trained model.

**Important Note:** Due to the random initialisation process used within sklearn's `DecisionTreeRegressor` class, you will need to fix the value of the `random_state` argument in order to get repeatable and predictable results.

_**Function Specifications:**_
* Should take two numpy `arrays` as input in the form `(X_train, y_train)`.
* Should return an sklearn `RandomForestRegressor` model.
* Set the `random_state` argument of the model to equal `42`
* The returned model should be fitted to the data.

_**Hint:**_
You may need to reshape the data within the function. You can use `.reshape(-1, 1)` to do this.


In [0]:
def train_model(X_train, y_train):
    from sklearn.ensemble import RandomForestRegressor
    reg = RandomForestRegressor(random_state =42, n_estimators=10)
    reg.fit(X_train.reshape(-1, 1),y_train.ravel())
    return reg

In [142]:
data = get_year_pop_by_income('High income')
(X_train, y_train), _ = sklearn_feature_response_split(data)

train_model(X_train, y_train).predict([[1960]])

array([7.86208256e+08])

_**Expected Outputs:**_
```python
train_model(X_train, y_train).predict([[1960]]) == array([7.86208256e+08])
```

### Question 4

We would now like to test on our testing data that we produced from Question 2. This test will give the Mean Absolute Error (MAE), which is given by:

$$
MAE = \frac{1}{N} \sum_{n=i}^N |p_i - y_i|
$$

where $p_i$ refers to the $i^{\rm th}$ prediction made from `X_test`, $y_i$ refers to the $i^{\rm th}$ value in `y_test`, and $N$ is the length of `y_test`.

_**Function Specifications:**_
* Should take a trained model and two `arrays` as input. This will be the `X_test` and `y_test` variables from Question 2. 
* Should return the residual sum of squares over the input from the predicted values of `X_test` as compared to values of `y_test`.
* The output should be a `float` rounded to 2 decimal places.

In [0]:
def test_model(model, X_test, y_test):
  y_pred = model.predict(X_test.reshape(-1,1))
  return np.round(np.sum(np.absolute(y_test.ravel() - y_pred)),2)

   

In [0]:
data = get_year_pop_by_income('High income')
(X_train, y_train), (X_test, y_test) = sklearn_feature_response_split(data)
lm = train_model(X_train, y_train)

In [152]:
test_model(lm, X_test, y_test)

16318333.2

_**Expected Outputs:**_
```python
test_model(lm, X_test, y_test) == 16318333.2
```